version: '3.8'

services:
  backend:
    build: ./lexum-library-api
    container_name: library-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./lexum-library-ui
    container_name: library-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge